// This file will be auto-generated by Supabase CLI:
//   npx supabase gen types typescript --project-id <id> > types/database.types.ts
// For now, use a manually maintained placeholder that mirrors the live schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // ------------------------------------------------------------------
      // profiles
      // ------------------------------------------------------------------
      profiles: {
        Row: {
          id: string;
          username: string;
          avatar_url: string | null;
          bio: string | null;
          points: number;
          total_matches: number;
          wins: number;
          losses: number;
          win_rate: number;
          rank: number;
          streak: number;
          is_verified: boolean;
          is_pro: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          avatar_url?: string | null;
          bio?: string | null;
          points?: number;
          total_matches?: number;
          wins?: number;
          losses?: number;
          win_rate?: number;
          rank?: number;
          streak?: number;
          is_verified?: boolean;
          is_pro?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          avatar_url?: string | null;
          bio?: string | null;
          points?: number;
          total_matches?: number;
          wins?: number;
          losses?: number;
          win_rate?: number;
          rank?: number;
          streak?: number;
          is_verified?: boolean;
          is_pro?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // ------------------------------------------------------------------
      // matches
      // ------------------------------------------------------------------
      matches: {
        Row: {
          id: string;
          game_id: string;
          match_type: string;
          status:
            | "pending"
            | "in_progress"
            | "completed"
            | "disputed"
            | "cancelled";
          wager_points: number;
          player_1_id: string;
          player_2_id: string | null;
          winner_id: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          game_id: string;
          match_type: string;
          status?:
            | "pending"
            | "in_progress"
            | "completed"
            | "disputed"
            | "cancelled";
          wager_points: number;
          player_1_id: string;
          player_2_id?: string | null;
          winner_id?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          game_id?: string;
          match_type?: string;
          status?:
            | "pending"
            | "in_progress"
            | "completed"
            | "disputed"
            | "cancelled";
          wager_points?: number;
          player_1_id?: string;
          player_2_id?: string | null;
          winner_id?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "matches_player_1_id_fkey";
            columns: ["player_1_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "matches_player_2_id_fkey";
            columns: ["player_2_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "matches_winner_id_fkey";
            columns: ["winner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };

      // ------------------------------------------------------------------
      // tournaments
      // ------------------------------------------------------------------
      tournaments: {
        Row: {
          id: string;
          title: string;
          game_id: string;
          status: "open" | "in_progress" | "completed" | "cancelled";
          entry_fee: number;
          prize_pool: number;
          max_participants: number;
          current_participants: number;
          start_time: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          game_id: string;
          status?: "open" | "in_progress" | "completed" | "cancelled";
          entry_fee?: number;
          prize_pool?: number;
          max_participants: number;
          current_participants?: number;
          start_time: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          game_id?: string;
          status?: "open" | "in_progress" | "completed" | "cancelled";
          entry_fee?: number;
          prize_pool?: number;
          max_participants?: number;
          current_participants?: number;
          start_time?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      // ------------------------------------------------------------------
      // tournament_entries
      // ------------------------------------------------------------------
      tournament_entries: {
        Row: {
          id: string;
          tournament_id: string;
          user_id: string;
          joined_at: string;
          final_rank: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tournament_id: string;
          user_id: string;
          joined_at?: string;
          final_rank?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tournament_id?: string;
          user_id?: string;
          joined_at?: string;
          final_rank?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tournament_entries_tournament_id_fkey";
            columns: ["tournament_id"];
            isOneToOne: false;
            referencedRelation: "tournaments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tournament_entries_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };

      // ------------------------------------------------------------------
      // linked_games
      // ------------------------------------------------------------------
      linked_games: {
        Row: {
          id: string;
          user_id: string;
          game_id: string;
          platform: string;
          external_id: string;
          display_name: string;
          is_verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          game_id: string;
          platform: string;
          external_id: string;
          display_name: string;
          is_verified?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          game_id?: string;
          platform?: string;
          external_id?: string;
          display_name?: string;
          is_verified?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "linked_games_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };

      // ------------------------------------------------------------------
      // wallet_transactions
      // ------------------------------------------------------------------
      wallet_transactions: {
        Row: {
          id: string;
          user_id: string;
          type: "earn" | "spend" | "wager" | "win" | "refund" | "purchase";
          points: number;
          description: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "earn" | "spend" | "wager" | "win" | "refund" | "purchase";
          points: number;
          description: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: "earn" | "spend" | "wager" | "win" | "refund" | "purchase";
          points?: number;
          description?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wallet_transactions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };

      // ------------------------------------------------------------------
      // ad_views
      // ------------------------------------------------------------------
      ad_views: {
        Row: {
          id: string;
          user_id: string;
          viewed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          viewed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          viewed_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ad_views_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };

    // Views and Functions are empty for now but must satisfy Supabase's GenericSchema
    // constraint: Views: Record<string, GenericView>, Functions: Record<string, GenericFunction>.
    // Using `{ [key: string]: never }` collapses the value type to `never`, which causes
    // the entire Schema type to fail the constraint and propagates `never` through every
    // Insert/Update/Row generic in the Supabase client. An empty object `{}` satisfies
    // Record<string, X> for any X because there are simply no entries to violate it.
    Views: {};
    Functions: {};
    Enums: {};
  };
}
